import { columns, Payment } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "728ed521",
      amount: 145,
      status: "pending",
      username: "Alice Smith",
      email: "alice.smith@gmail.com",
    },
    {
      id: "728ed522",
      amount: 230,
      status: "success",
      username: "Bob Johnson",
      email: "bob.johnson@gmail.com",
    },
    {
      id: "728ed523",
      amount: 89,
      status: "failed",
      username: "Carol White",
      email: "carol.white@gmail.com",
    },
    {
      id: "728ed524",
      amount: 312,
      status: "pending",
      username: "David Brown",
      email: "david.brown@gmail.com",
    },
    {
      id: "728ed525",
      amount: 178,
      status: "success",
      username: "Eve Davis",
      email: "eve.davis@gmail.com",
    },
    {
      id: "728ed526",
      amount: 94,
      status: "failed",
      username: "Frank Miller",
      email: "frank.miller@gmail.com",
    },
    {
      id: "728ed527",
      amount: 205,
      status: "pending",
      username: "Grace Lee",
      email: "grace.lee@gmail.com",
    },
    {
      id: "728ed528",
      amount: 137,
      status: "success",
      username: "Hank Wilson",
      email: "hank.wilson@gmail.com",
    },
    {
      id: "728ed529",
      amount: 66,
      status: "failed",
      username: "Ivy Taylor",
      email: "ivy.taylor@gmail.com",
    },
    {
      id: "728ed530",
      amount: 289,
      status: "pending",
      username: "Jack Moore",
      email: "jack.moore@gmail.com",
    },
    {
      id: "728ed531",
      amount: 150,
      status: "success",
      username: "Kelly Anderson",
      email: "kelly.anderson@gmail.com",
    },
    {
      id: "728ed532",
      amount: 103,
      status: "failed",
      username: "Liam Clark",
      email: "liam.clark@gmail.com",
    },
    {
      id: "728ed533",
      amount: 224,
      status: "pending",
      username: "Mia Lewis",
      email: "mia.lewis@gmail.com",
    },
    {
      id: "728ed534",
      amount: 191,
      status: "success",
      username: "Noah Walker",
      email: "noah.walker@gmail.com",
    },
    {
      id: "728ed535",
      amount: 78,
      status: "failed",
      username: "Olivia Hall",
      email: "olivia.hall@gmail.com",
    },
    {
      id: "728ed536",
      amount: 305,
      status: "pending",
      username: "Peter Young",
      email: "peter.young@gmail.com",
    },
    {
      id: "728ed537",
      amount: 162,
      status: "success",
      username: "Quinn King",
      email: "quinn.king@gmail.com",
    },
    {
      id: "728ed538",
      amount: 87,
      status: "failed",
      username: "Rose Scott",
      email: "rose.scott@gmail.com",
    },
    {
      id: "728ed539",
      amount: 239,
      status: "pending",
      username: "Sam Green",
      email: "sam.green@gmail.com",
    },
    {
      id: "728ed540",
      amount: 114,
      status: "success",
      username: "Tina Adams",
      email: "tina.adams@gmail.com",
    },
    {
      id: "728ed541",
      amount: 196,
      status: "failed",
      username: "Uma Baker",
      email: "uma.baker@gmail.com",
    },
    {
      id: "728ed542",
      amount: 253,
      status: "pending",
      username: "Victor Hill",
      email: "victor.hill@gmail.com",
    },
    {
      id: "728ed543",
      amount: 130,
      status: "success",
      username: "Wendy Turner",
      email: "wendy.turner@gmail.com",
    },
    {
      id: "728ed544",
      amount: 71,
      status: "failed",
      username: "Xander Phillips",
      email: "xander.phillips@gmail.com",
    },
    {
      id: "728ed545",
      amount: 278,
      status: "pending",
      username: "Yara Campbell",
      email: "yara.campbell@gmail.com",
    },
    {
      id: "728ed546",
      amount: 145,
      status: "success",
      username: "Zack Mitchell",
      email: "zack.mitchell@gmail.com",
    },
    {
      id: "728ed547",
      amount: 99,
      status: "failed",
      username: "Abby Parker",
      email: "abby.parker@gmail.com",
    },
    {
      id: "728ed548",
      amount: 210,
      status: "pending",
      username: "Ben Evans",
      email: "ben.evans@gmail.com",
    },
    {
      id: "728ed549",
      amount: 167,
      status: "success",
      username: "Clara Roberts",
      email: "clara.roberts@gmail.com",
    },
    {
      id: "728ed550",
      amount: 83,
      status: "failed",
      username: "Dan Stewart",
      email: "dan.stewart@gmail.com",
    },
    {
      id: "728ed551",
      amount: 295,
      status: "pending",
      username: "Ella Wright",
      email: "ella.wright@gmail.com",
    },
    {
      id: "728ed552",
      amount: 120,
      status: "success",
      username: "Finn Edwards",
      email: "finn.edwards@gmail.com",
    },
    {
      id: "728ed553",
      amount: 154,
      status: "failed",
      username: "Gina Harris",
      email: "gina.harris@gmail.com",
    },
    {
      id: "728ed554",
      amount: 231,
      status: "pending",
      username: "Henry Martin",
      email: "henry.martin@gmail.com",
    },
    {
      id: "728ed555",
      amount: 98,
      status: "success",
      username: "Iris Nelson",
      email: "iris.nelson@gmail.com",
    },
    {
      id: "728ed556",
      amount: 177,
      status: "failed",
      username: "Jake Carter",
      email: "jake.carter@gmail.com",
    },
    {
      id: "728ed557",
      amount: 266,
      status: "pending",
      username: "Kate Turner",
      email: "kate.turner@gmail.com",
    },
    {
      id: "728ed558",
      amount: 133,
      status: "success",
      username: "Leo Allen",
      email: "leo.allen@gmail.com",
    },
    {
      id: "728ed559",
      amount: 70,
      status: "failed",
      username: "Mona Reed",
      email: "mona.reed@gmail.com",
    },
    {
      id: "728ed560",
      amount: 302,
      status: "pending",
      username: "Nick Cook",
      email: "nick.cook@gmail.com",
    },
    {
      id: "728ed561",
      amount: 159,
      status: "success",
      username: "Olivia Bell",
      email: "olivia.bell@gmail.com",
    },
    {
      id: "728ed562",
      amount: 85,
      status: "failed",
      username: "Paul Gray",
      email: "paul.gray@gmail.com",
    },
    {
      id: "728ed563",
      amount: 245,
      status: "pending",
      username: "Quinn James",
      email: "quinn.james@gmail.com",
    },
    {
      id: "728ed564",
      amount: 112,
      status: "success",
      username: "Rose Kelly",
      email: "rose.kelly@gmail.com",
    },
    {
      id: "728ed565",
      amount: 193,
      status: "failed",
      username: "Sam Brooks",
      email: "sam.brooks@gmail.com",
    },
    {
      id: "728ed566",
      amount: 270,
      status: "pending",
      username: "Tina Ford",
      email: "tina.ford@gmail.com",
    },
    {
      id: "728ed567",
      amount: 138,
      status: "success",
      username: "Umar Hughes",
      email: "umar.hughes@gmail.com",
    },
    {
      id: "728ed568",
      amount: 77,
      status: "failed",
      username: "Vera Long",
      email: "vera.long@gmail.com",
    },
    {
      id: "728ed569",
      amount: 284,
      status: "pending",
      username: "Will Price",
      email: "will.price@gmail.com",
    },
    {
      id: "728ed570",
      amount: 161,
      status: "success",
      username: "Xena Ward",
      email: "xena.ward@gmail.com",
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div>
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  );
};

export default PaymentsPage;
